# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BidKab' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BidKab
	pod 'GoogleMaps'
  	pod 'GooglePlaces'
  	pod 'GooglePlacePicker'
  	pod 'SnapKit', '~> 4.0.0'
  	pod 'Alamofire'
  	pod 'Kingfisher'
  	pod 'SwiftyJSON'
  	pod 'IQKeyboardManagerSwift'
  	pod 'MaterialTextField', '~> 0.2'
  	pod 'InputMask'
  	pod 'Firebase/Auth'
  	pod 'Firebase/Core'
  	pod 'Firebase/Messaging'
  	pod 'VisualEffectView'
  	pod 'SVProgressHUD'
  	pod 'Socket.IO-Client-Swift', '~> 12.0.0'
  	pod 'BSImagePicker'
  	pod 'Cosmos', '~> 15.0'
end
